#person:
#  last-name: ${random.uuid}
#  age: 20
#  boss: true
#  birth: 2019/10/1
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - wangwu
#    - zhaoliu
#  dog:
#    name: 'угеуге\n'
#    age: 2


#server:
#  port: 8088
#spring:
#  profiles:
#    active: dev
#---
#server:
#  port: 8089
#spring:
#  profiles: dev
#---
#server:
#  port: 8082
#spring:
#  profiles: test
server:
  servlet:
    context-path: /boot

